language: python
python: [2.7, 3.4, 3.5, 3.6]
env:
# Remove following environment variables after nirum-python 0.6.0 is released.
- DEVRUNTIME_REPO=dahlia/nirum-python DEVRUNTIME_REF=transport
install:
- pip install tox-travis
- mkdir "$HOME/bin"
script:
- tox -e devruntime
- tox
- tox -e docs
- '[[ "$TRAVIS_TAG" = "" ]] || [[ "$TRAVIS_TAG" = "$(python setup.py --version)" ]]'
- |
    if git show --format=%B --quiet "$TRAVIS_COMMIT_RANGE$TRAVIS_TAG" | grep '\[changelog skip\]' > /dev/null; then
      echo "Skip changelog checker..."
    elif [[ "$TRAVIS_TAG" != "" ]]; then
      ! grep -i "to be released" README.rst
    else
      [[ "$(git diff --name-only "$TRAVIS_COMMIT_RANGE" | grep CHANGES\.rst)" != "" ]]
    fi
